FROM python:3.9.1

RUN pip install pandas sqlalchemy psycopg2

WORKDIR /app

COPY ingest_1.2.6_only_zone_data.py ingest_1.2.6_only_zone_data.py

ENTRYPOINT ["python", "ingest_1.2.6_only_zone_data.py"]

