sync_config:
  access_token_secret_name: mage_git_access_token
  auth_type: https
  branch: main
  email: sndselecta@gmail.com
  enable_git_integration: null
  remote_repo_link: https://github.com/SoundBoySelecta/de-zc-mage_synced_data.git
  repo_path: /home/src
  sync_submodules: false
  username: soundboyselecta
